# Custom Language File for Launcher Customizer

[ejs.app]
title = "쥬빠비팀"

[ejs.landing]
mediaGitHubURL = "https://github.com/qdakim/jubbabi"
mediaTwitterURL = "#"
mediaInstagramURL = "#"
mediaYouTubeURL = "#"
mediaDiscordURL = "#"
mediaAfreecaTVURL = "#"
screenshotsTooltip = "스크린샷"

[ejs.settings]
sourceGithubLink = "https://github.com/qdakim/jubbabi"
supportLink = "https://github.com/qdakim/jubbabi/issues"

[ejs.welcome]
welcomeHeader = "쥬빠비팀"
welcomeDescription = ""
welcomeDescCTA = "계속하기 버튼을 눌러 계속 진행하여 주세요."